export ZSH=/etc/zsh

# Load all of the config files
for config_file ($ZSH/lib/*.zsh) source $config_file

# Load and run compinit
autoload -U compinit
compinit -i

set LC_CTYPE=en_US.UTF-8
set LC_ALL=en_US.UTF-8
set LANG=en_US.UTF-8

export GREP_OPTIONS='--color=auto'

precmd () {print -Pn "\e]2; %~/ \a"}
preexec () {print -Pn "\e]2; %~/ \a"}

